# Makefile.linux

setup: venv
	. .venv/bin/activate && python -m pip install --upgrade pip
	. .venv/bin/activate && pip install -r requirements.txt
	. .venv/bin/activate && python -m pip install ipykernel install --name .env --user

venv:
	test -d .venv || python -m venv .venv

test-local:
	echo "Not implemented yet"

build-local:
	echo "Not implemented yet"

build-dev:
	echo "Not implemented yet"

build-prod:
	echo "Not implemented yet"

rebuild-knowledge-base:
	echo "Not implemented yet"
